encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "wiki"
urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/<str:page>", views.page, name="page"),
    path("random", views.random, name="random"),
    path("new", views.new, name="new"),
    path("edit/<str:page>", views.edit, name="edit"),
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from markdown2 import Markdown
markdowner = Markdown()
from django import forms
import random as ran
from math import floor

class NewEntryForm(forms.Form):
    title = forms.CharField(label="Title")
    content = forms.CharField(widget=forms.Textarea(attrs={"rows": "5", "cols":"5"}))
class EditForm(forms.Form):
    title = forms.CharField(widget = forms.HiddenInput())
    content = forms.CharField(widget=forms.Textarea())

from . import util, myutil


def index(request):
    if request.method == "POST":
        entries = []
        items = util.list_entries()
        for item in items:
            if item.lower() == request.POST["q"].lower():
                return HttpResponseRedirect(f"wiki/{item}")
            print(item.lower().find(request.POST['q'].lower()) != -1)
            if item.lower().find(request.POST['q'].lower()) != -1:
                entries.append(item)
        return render(request, "encyclopedia/index.html", {
            "entries": entries,
            "search": True,
        })
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries(),
        "search": False,
    })

def page(request, page):   
    md = util.get_entry(page)
    if not md == None:
        content = {
            "pagecontent": myutil.convertToHtml(md),
            "title": page
        }
        try:
            if request.GET["success"] == "create":
                content["type"] = "success"
                content["message"] = "new entry added successfully"
            elif request.GET["success"] == "edit":
                content["type"] = "success"
                content["message"] = "entry edited successfully"

        except:
            pass
        return render(request, "encyclopedia/page.html",content)
    else:
        return render(request, "encyclopedia/page.html",{
            "pagecontent": f"<h1>'{page}' does not exist!</h1>",
        })

def random(request):
    pages = util.list_entries()
    total = len(pages)
    number = floor(ran.random() * total)
    return HttpResponseRedirect(f"/wiki/{pages[number]}")

def new(request):
    if request.method == "POST":
        form = NewEntryForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            print(data)
            if not util.get_entry(data["title"].capitalize()):
                util.save_entry(data["title"].capitalize(), data["content"])
                return HttpResponseRedirect(f"/wiki/{data["title"]}?success=create")
            else:
                return render(request, "encyclopedia/form.html", {
                    "new":True,
                    "type": "error",
                    "message": "this page already exists, please edit the original form, or use a different title",
                    "form":form,
                })
        else:
            return render(request, "encyclopedia/form.html", {
                "new":True,
                "type": "error",
                "message": "form data is not valid",
                "form":form,
            })

    return render(request, "encyclopedia/form.html", {
        "new":True,
        "form":NewEntryForm,
    })

def edit(request, page):
    if request.method == "POST":
        form = NewEntryForm(request.POST)
        if form.is_valid():
            content = form.cleaned_data["content"].encode()
            title = form.cleaned_data["title"]
            print(request.POST["title"])
            util.save_entry(title, content)
            return HttpResponseRedirect(f"/wiki/{title}?success=edit")
    content = util.get_entry(page)
    return render(request, "encyclopedia/form.html",{
                "new": False,
                "title": page,
                "form": EditForm({"title": page, "content": content}) 
    })

encyclopedia/templates/encyclopedia/form.html
{% extends "encyclopedia/layout.html" %} {% block title %} Encyclopedia
{%endblock %} {% block body %} {% if new %}
<h1>Add New Entry</h1>
{% else %}
<h1>edit {{title}}</h1>
{% endif %}

<form
	action=""
	method="post">
	{% csrf_token %} {{ form }}
	<button>add new entry</button>
</form>

{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %} {% block title %} Encyclopedia
{%endblock %} {% block body %} {% if search %}
<h1>Search</h1>
{% else %}
<h1>All Pages</h1>
{% endif %}

<ul>
	{% for entry in entries %}
	<li><a href="{% url 'wiki:page' entry %}">{{ entry }}</a></li
	>{% empty %}
	<li>No Results, Please try again!</li>
	{% endfor %}
</ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
	<head>
		<title>{% block title %}{% endblock %}</title>
		<link
			rel="stylesheet"
			href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
			integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
			crossorigin="anonymous" />
		<link
			href="{% static 'encyclopedia/styles.css' %}"
			rel="stylesheet" />
	</head>
	<body>
		<div class="row">
			<div class="sidebar col-lg-2 col-md-3">
				<h2>Wiki</h2>
				<form
					action="{% url 'wiki:index' %}"
					method="POST">
					{% csrf_token %}
					<input
						class="search"
						type="text"
						name="q"
						placeholder="Search Encyclopedia" />
				</form>
				<div>
					<a href="{% url 'wiki:index' %}">Home</a>
				</div>
				<div>
					<a href="{% url 'wiki:new' %}">Create New Page</a>
				</div>
				<div>
					<a href="{% url 'wiki:random' %}">Random Page</a>
				</div>
				{% block nav %} {% endblock %}
			</div>
			<div class="main col-lg-10 col-md-9">
				{% if message %}
				<p class="{{ type }} message">{{ message }}</p>
				{% endif %} {% block body %} {% endblock %}
			</div>
		</div>
	</body>
</html>

encyclopedia/templates/encyclopedia/new.html
{% extends "encyclopedia/layout.html" %} {% block title %} Encyclopedia
{%endblock %} {% block body %}

<h1>Add New Entry</h1>


<form
	action=""
	method="post">
	{% csrf_token %} {{ form }}
	<button>add new entry</button>
</form>

{% endblock %}

encyclopedia/templates/encyclopedia/page.html
{% extends "encyclopedia/layout.html" %}
{% block title %} 
Encyclopedia 
{%endblock %}
{% block body %} 
{% if title %}
    <a href="{% url 'wiki:edit' title %}">edit</a>
{% endif %}
    {{ pagecontent|safe }} 
{% endblock %}